[package]
name = "vpx-encode"
description = "Rust interface to libvpx encoder"
repository = "https://github.com/astraw/vpx-encode"
authors = ["Andrew Straw <strawman@astraw.com>", "Ram Kaniyur <quadrupleslap@gmail.com>"]
license = "MIT"
version = "0.6.2"
edition = "2018"

[dependencies]
libvpx-native-sys = "5.0.13"
thiserror = "1.0.33"

[features]
vp9 = []
backtrace = []
ffi-generate = ["libvpx-native-sys/generate"]

[package.metadata.docs.rs]
features = [ "vp9" ]
